### ISSUE TITLE
[환경설정]: 의존성 추가

### ISSUE THREAD

**Issue by dkumylove** [PROJECT-SUNDO/sundo#7]
### 설명
- 의존성 추가

### 🗒 체크리스트

- [x] spring-webmvc
- [x] spring-security
- [x] lombok
- [x] Thymeleaf + layout
- [x] h2
- [x] poi-ooxml (엑셀의존성)
- [x] modelmapper
- [x] JDBC (DB드라이버)
- [x] JPA
- [x] Querydsl
- [x] devtools (리로딩)
- [x] Validation
- [ ] email
- [x] JBCrypt
- [x] slf4j (log)
- [x] logback (log)
- [x] 한글깨짐

**Comment by yunii118** [comment]
devtools -> spring boot 전용, 적용 불가능
